module.exports = {
  USER_REGISTRATION: 'User registered successfully',
  EMAIL_EXISTS: 'Email already exists',
  INTERNAL_SERVER_ERROR: 'Internal server error occurred',
  LOGIN_SUCCESS: 'Login Successful',
  INVALID_CREDENTIALS: 'Invalid email or password',
  UNAUTHORIZED: 'Token is Required or Invalid',
  FORBIDDEN: 'Forbidden',
  CATEGORY_EXISTS: 'Category already exists',
  CATEGORY_CREATED: 'Category created successfully',
  CATEGORIES_FETCHED: 'Categories fetched successfully',
  CATEGORY_NOT_FOUND: 'Category not found',
  CATEGORY_DELETED: 'Category deleted successfully',
  CATEGORY_UPDATED: 'Category updated successfully',
  PRODUCT_CREATED: 'Product created successfully',
  SKU_EXISTS: 'Product with this SKU already exists',
  PRODUCTS_FETCHED: 'Products fetched successfully',
  PRODUCT_NOT_FOUND: 'Product not found',
  PRODUCT_DELETED: 'Product deleted successfully',
  PRODUCT_UPDATED: 'Product updated successfully',
  PRODUCT_FETCHED: 'Product fetched successfully',
  CART_ITEM_ADDED: 'Product added to cart',
  CART_FETCHED: 'Cart fetched successfully',
  CART_UPDATED: 'Cart updated successfully',
  CART_ITEM_REMOVED: 'Cart item removed successfully',
  CART_NOT_FOUND: 'Cart item not found',
  INSUFFICIENT_STOCK: 'Requested quantity exceeds available stock',
  WISHLIST_ALREADY_EXISTS: 'Product already exists in wishlist',
  WISHLIST_NOT_FOUND: 'Wishlist item not found',
  WISHLIST_ADDED: 'Product added to wishlist',
  WISHLIST_FETCHED: 'Wishlist fetched successfully',
  WISHLIST_REMOVED: 'Product removed from wishlist',
  ORDER_CREATED: 'Order placed successfully',
  ORDERS_FETCHED: 'Orders fetched successfully',
  ORDER_FETCHED: 'Order fetched successfully',
  ORDER_CANCELLED: 'Order cancelled successfully',
  ORDER_NOT_FOUND: 'Order not found',
  CART_EMPTY: 'Cart is empty',
  PAYMENT_SUCCESS: 'Payment updated successfully',
  RAZORPAY_ORDER_CREATED: 'Razorpay order created successfully',
  PAYMENT_SUCCESS: 'Payment verified successfully',
  ORDERS_FETCHED_SUCCESSFULLY: 'Orders fetched successfully',
  ORDER_FETCHED_SUCCESSFULLY: 'Order fetched successfully',
  ORDER_STATUS_UPDATED: 'Order status updated successfully',
};
